### ISSUE TITLE
Uncaught ReferenceError: reportEndStamp is not defined

### ISSUE THREAD

**Issue by jvanderzande** [amrij/zonnepanelen#19]
@mirakels , This PR #15  introduced variable reportEndStamp, but it seems it isn't declared, so is giving an error. 
File changes in the commit:
https://github.com/amrij/zonnepanelen/commit/7e7c62f59d44a150e3d2ea503a21d5fb68bd932e#diff-2e31b28f54a10d4ce95bbcf4850675c4

Jos

**Comment by mirakels** [comment]
Yes that is wrong. that little patch change  from 'tomorrow' to 'reportEndStamp' shouldn't have been part of this. Sorry about that.
It is part of my internal code  to update alls those unclear date/time names in whole script....
The simple fix for it would be to change reportEndStamp back to tomorrow. I guess it is easiest if you guys do that directly in the master tree.

**Comment by jvanderzande** [comment]
Ok, will do... thanks
