### ISSUE TITLE
dagopbrengst grafiek

### ISSUE THREAD

**Issue by spiralshapeturtle** [amrij/zonnepanelen#44]
In plaats van GoT hier maar eens de vraag stellen. 

Op dit moment zijn de grafieken van de develop blauw ingekleurd. Echter door alle grijze lijnen (voorgaande dagen) is het niet heel overzichtelijk wat de karakteristiek is van de voorgaande dag. Er is even een moment geweest deze week dat in de develop blauw en groen werd ingekleurd.

Mijn voorstel is:
-in rust de grafiek laten zoals hij nu is, blauw + dfdfdf hex code voor grijze lijnen
-bij mouseover zie je de opbrengsten van vorige dagen, maar het is overzichtelijker als de geselecteerde dag dan, net als de blauwe grafiek, een kleur zou krijgen -> groen.

**Comment by jvanderzande** [comment]
Ik heb een voorstel om de volgende aanpassingen te maken:
- tooltip te fixeren links bovenaan onder de legenda, ipv bij de muispointer.
- geselecteerde lijn groen maken en toevoegen in de legenda
- als $ingr=1, dan ook het vlak vullen met groen, hetzelfde als de blauwe "vandaag" lijn.

$ingr=0:
![image](https://user-images.githubusercontent.com/13818504/57486376-50623480-72ae-11e9-875b-2b2487074183.png)
$ingr=1
![image](https://user-images.githubusercontent.com/13818504/57486615-a505af80-72ae-11e9-88ef-b84abe247a6c.png)

Als jullie dit een goed ontwerp vinden zal ik een commit doen.

**Comment by mirakels** [comment]
lijkt me een goed plan! Ik had de tooltip lokaal ook al gefixeerd.
Maar het netjes laten kleuren van de geselecteerde lijn lukte me niet zo goed (en er dan ook voor te zorgen dat bij de mouseOut van de graph alle tooltip aanpassingen weer ongedaan worden gemaakt..)

**Comment by spiralshapeturtle** [comment]
Jos ziet er mooi uit, absoluut voorstander!

**Comment by jvanderzande** [comment]
Ik wil graag de huidige development eerst naar master overzetten voordat ik deze commit maak.
Reden is dat het goed werkt, maar het genereerde een berg aan highchart errors in de developer console. Om dat te fixen moeten we een update van highcharts doen. Op zich niet spannend waren het niet dat dan de swap tussen inverter charts en panel charts niet meer werkt. Daarvoor heb ik nu een oplossing, die denk ik ook beter is door de DIV 's the verbergen ipv de charts html leeg te maken en opnieuw te genereren, maar dat betekent een wat grotere aanpassing.
Dus laten we eerst de huidige development correct maken. @mirakels, kan jij nog even kijken naar de laatste PR, ik heb daar een comment in gemakt dat we nog wat css info missen voor de nieuwe DIV van de sun voor mobiel en tablet.

**Comment by amrij** [comment]
Laten we eerst de huidige development overzetten naar de master en dan dit verder uitwerken.
Ik heb gisteren een aanpassing voor de moonphase en sun gedaan voor mobiel en tablet.
op mijn mobiel werkt dit goed.

Het voorstel ziet er goed uit.

**Comment by mirakels** [comment]
Ja een goed moment om dev naar master te brengen.

**Comment by mirakels** [comment]
over de charts switchen betreft. Ik heb de daygraph en power_chart_body en nog een eigen chart over elkaar liggen en selecteer ze door over de inverte, p1_meter of het huis te hoveren. bij de mouseover zet ik dan de z-index van de gewenste graph wat hoger. Maar ik weet niet of dat bij de nieuwe highcharts ook nog werkt. Lijkt me wel want de z-index wordt niet door highcharts gemanaged lijkt me.

       function BottomLeftChart(g) {  // Select graph for left corner
                //document.getElementById("box_daygraph").style.display = (g == "daygraph") ? "initial" : "none";
                //document.getElementById("box_utilitygraph").style.display = (g == "utility") ? "initial" : "none";
                //document.getElementById("box_power_chart_body").style.display = (g == "powerchart") ? "initial" : "none";
                document.getElementById("box_daygraph").style.zIndex = (g == "daygraph") ? "31" : "30";
                document.getElementById("box_utilitygraph").style.zIndex = (g == "utility") ? "31" : "30";
                document.getElementById("box_power_chart_body").style.zIndex = (g == "powerchart") ? "31" : "30";
        }

**Comment by jvanderzande** [comment]
Nadat master geupdated is zal ik in stappen de aanpassingen committen zodat je kan testen.
ik heb op dit moment de nieuwe versies van highcharts als "newhighcharts.js" en "newhighcharts-more.js" in de js directory gezet en ben daarmee aan het testen in een kopie van zonnepanelen.php. Zo kunnen ze makkelijk naast elkaar draaien, maar de commits gaan de oude versie overschrijven, dus we moeten even goed testen voordat het naar master gaat. 

De aanpassing om de hide/show te doen heb ik als volgt gedaan:
oud:
```
document.getElementById("chart_vermogen").innerHTML = "";
document.getElementById("chart_energy").innerHTML = "";
```

nieuw:
```
document.getElementById("box_chart_vermogen").style.display = "none"
document.getElementById("box_chart_energy").style.display = "none"
```
en om een <DIV> weer te laten zien:
```
document.getElementById("box_chart_vermogen").style.display = "block"
document.getElementById("box_chart_energy").style.display = "block"

```

**Comment by mirakels** [comment]
ik had ook getest met style.display, maar op een of andere manier werkte dat niet lekker. Weet niet meer waarom. 'initial' werkte beter dan 'block'. Maar ik weet de details niet meer...

**Comment by jvanderzande** [comment]
Master geupdate met de laatste development versie en de update voor highcharts beschikbaar gemaakt in development.  Het is een redelijk grote sprong van v5 naar v7.1.1. 
Een van de nieuwe standaards is dat nu de "vandaag" grafiek weg-fade als je op een tijd staat waar nog geen data voor beschikbaar is. Ik  heb daar nog geen optie voor gevonden.  Ook een 2de versie toegevoegd waar de bovenstaande wijzigingen in zitten: zonnepanelen_ani.php. Dit zit nu express apart zodat we goed het verschil van de basis upgrade kunnen zien.  Speel er even mee en ik hoor wel wat jullie ervan vinden.

**Comment by amrij** [comment]
Jos,

 

Ik heb het gezien. Het is een mooi stukje werk dat we samen en met Marcel hebben gemaakt.

 

Ik heb een aanpassing op de versie zonnepanelen_ani.php gemaakt. 

Dit betreft de kleuren die in config.php staan.

 

Verder zie ik dat er veel error worden gegenereerd in zonnepanelen_ani.php. Dit betreft highcharts.js fouten.

Ik heb nog niet kunnen achterhalen wat de oorzaak hiervan is.

 

Groet,

 

André

 

Van: Jos van der Zande <notifications@github.com> 
Verzonden: zaterdag 11 mei 2019 11:44
Aan: amrij/zonnepanelen <zonnepanelen@noreply.github.com>
CC: amrij <a.m.rijkeboer@am-rijkeboer.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [amrij/zonnepanelen] dagopbrengst grafiek (#44)

 

Master geupdate met de laatste development versie en de update voor highcharts beschikbaar gemaakt in development. Het is een redelijk grote sprong van v5 naar v7.1.1. een van de nieuwe standaards is dat nu de "vandaag" grafiek weg-fade als je op een tijd staat waar nog data voor beschikbaar is. Ik heb daar nog geen optie voor gevonden. Ook een 2de versie toegevoegd waar de bovenstaande wijzigingen in zitten: zonnepanelen_ani.php. Dit zit nu express apart zodat we goed het verschil van de basis upgrade kunnen zien. Speel er even mee en ik hoor wel wat jullie ervan vinden.

**Comment by jvanderzande** [comment]
@amrij , heb je wel de highcharts.js & highcharts-more.js vervangen met de nieuwe versie?

**Comment by spiralshapeturtle** [comment]
Hey Jos

top stukje werk! 

De afgelopen dag heb ik hem default gebruikt, waarbij de huidige dag blauw is en de voorgaande dag groen. Maar dat geeft toch nog onoverzichtelijke beeld op kleine schermen.

Met deze instellingen ziet het er beter uit, echter is de kleur grijs te donker waardoor je nog geen clean view hebt in je eerste oogopslag. Is het mogelijk dat jullie de overige lijnen ook als variabele kleur opnemen in de config file, ik heb het nu hard coded gedaan.

```
$ingr = 1; // 0 = alleen lijn, 1 = gevuld

$kleur = '#4169E1'; // kleur royalbleu voor actuele dag
$kleur1 = '#dfdfdf'; // kleur groen voor lijn voorafgaande dag inverter grafiek (grijs = '#d4d0d0')
$kleur2 = '#009900'; // kleur groen voor lijn actueel paneel
```

**Comment by spiralshapeturtle** [comment]
@jvanderzande is het bij jou ook spontaan defect vanmorgen op de beide develop site?

<img width="378" alt="image" src="https://user-images.githubusercontent.com/16855935/57578415-1f3f5b00-748c-11e9-8564-1c15ab209826.png">

**Comment by jvanderzande** [comment]
@rodeho, Dat lijkt een CSS probleempje die waarschijnlijk in je cache herladen is.
Iets wat in je local versie staat misschien?
Email me anders even een linkje van de site en kijk ik even in developer mode welke CSS er geladen wordt.
EDIT: linkje weer gevonden en je lijkt je zonnepanelen-local.css te missing in de setup:
![image](https://user-images.githubusercontent.com/13818504/57579779-481e1b00-74a1-11e9-8e19-b90c6c196fdc.png)

**Comment by jvanderzande** [comment]
> Met deze instellingen ziet het er beter uit, echter is de kleur grijs te donker waardoor je nog geen clean view hebt in je eerste oogopslag. Is het mogelijk dat jullie de overige lijnen ook als variabele kleur opnemen in de config file, ik heb het nu hard coded gedaan.

Lijkt me prima om een default kleur op te nemen in de config.php voor de overige lijnen.

**Comment by amrij** [comment]
Deze optie heb ik al in zonnepanelen_ani.php en in config.php gezet

**Comment by jvanderzande** [comment]
Top!
is iedereen tevreden met de aanpassingen in zonnepanelen_ani.php?
Als dat zo is zal ik  hem mergen met zonnepanelen.php en verwijderen. 
Ik heb trouwens ook gekeken om in de Vermogen Inverter grafiek een optie om een voortschrijdend gemiddelde te laten zien ipv de werkelijke waarde, met de optie in de grafiek om tussen de echte waarden en het gemiddelde te schakelen. In de config.php kan je aangeven voor hoeveel punten je het gemiddelde wilt. 2 of 3 werkt prima en maakt de grafiek veel rustiger zoals @rodeho aangeeft in #45 .
Originele waarden:
![image](https://user-images.githubusercontent.com/13818504/57586658-441de780-74f9-11e9-90a6-e5f8af8b7217.png)
2 punts gemiddelde:
![image](https://user-images.githubusercontent.com/13818504/57586678-ba224e80-74f9-11e9-93c0-f4341be2d2f3.png)
3 punts gemiddelde:
![image](https://user-images.githubusercontent.com/13818504/57586665-67489700-74f9-11e9-8dff-695dcc56c0ee.png)

Ik zal dit na de Merge ook beschikbaar maken zodat jullie kunnen kijken of het wat is.

**Comment by spiralshapeturtle** [comment]
Ha Jos

het ziet er goed uit, kan je in deze merge dan ook de wijziging meenemen voor de grijze lijnen ouder dan gisteren? @amrij gaf aan dat dit er in zit maar dat is slechts voor dag 14 dag 1-13 zijn niet te veranderen van grijstint.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/16855935/57586839-fbb3f900-74fb-11e9-9fbc-b5c0384da4ba.png">

**Comment by spiralshapeturtle** [comment]
Ik zie net dat kleurg$ al opgenomen is vandaag ;-) tnx.

Het is geen caching issue, ik ga ff de nieuwste develop downloaden kijken of dat mijn panelen plaat hersteld.

**Comment by amrij** [comment]
Wat mij betreft kan het naar zonnepanelen.php.
Kun je ook de bovenstaande optie er bij opnemen?

**Comment by jvanderzande** [comment]
Aanpassingen staan nu in de development branch. Vergeet niet om deze regel op te nemen in config.php:
`$Gem_Verm =2 ;      // bereken het gemiddelde van x metingen om de grafiek wat minder te laten fluctueren
`
.. en zet de waarden op het aantal punten waar get gemiddelde van moet worden getoond als default. Rechts bovenin de Vermogens grafiek komt een menu met opties als de waarde groter is als 1 om te kunnen schakelen naar werkelijke waarde.

**Comment by jvanderzande** [comment]
> Het is geen caching issue, ik ga ff de nieuwste develop downloaden kijken of dat mijn panelen plaat hersteld.

Dat is ook wat mijn EDIT in die post aangaf: Je moet de eigen zonnepanelen-local.php nog naar die nieuwe site kopiëren want anders is er geen goede css voor alle panelen en krijg je dit soort problemen.

**Comment by spiralshapeturtle** [comment]
Jos up an running, ik ga ff testen voor je. tnx

**Comment by jvanderzande** [comment]
Laatste wijzigingen aangebracht vandaag:
- ander voortschrijdend gemiddelde berekening toegepast
- kleuren schema voor P1 grafieken gelijk gemaakt aan Inverter grafieken door gebruik te maken van de kleuren die in config.php gedefinieerd zijn: 
![image](https://user-images.githubusercontent.com/13818504/57627325-12a82900-7598-11e9-9d45-af4df30a44ba.png)
- aanpassingen aan de panel-hover logica omdat dit bij veel snelle muisbewegingen niet altijd goed ging.

**Comment by spiralshapeturtle** [comment]
Jos

mooie look, zou je jouw kleuren config eens willen delen? Lijkt mij goed om deze als default op te nemen.

**Comment by jvanderzande** [comment]
Hoi Rob,

 

Ik gebruik de standaard kleuren, maar heb de “gisteren” kleur dezelfde gemaakt als de overige dagen omdat ik die niet apart hoef te zien. (zie hieronder)

Als je de laatste development versie gebruikt zal die bij jouw er ook zo uitzien.

Gr./Jos

 

$kleur = '#4169E1';  // kleur royalbleu voor actuele dag

$kleur1 = '#d4d0d0'; // kleur groen voor lijn voorafgaande dag inverter grafiek (grijs = '#d4d0d0')

$kleur2 = '#009900'; // kleur groen voor lijn actueel paneel

$kleurg = '#d4d0d0'; // kleur grijs voor lijn overige dagen / panelen

**Comment by amrij** [comment]
Jos,

Ik vind de kleuren voor de p1 grafieken niet zo geslaagd.
Ik heb bij mij nu een variant draaien waarbij de rgba kleuren in de config.php zijn opgenomen.
Zal ik deze naar development uploaden?

**Comment by mirakels** [comment]
Even een vraagje. Waarom maken jullie overal gebruik van <?php  echo $kleur ?>
en gewoon een javascript var zoals ook met veel andere plekken gebeurd? 
Het maakt de code veel leesbaarder, en maakt het mogelijk om in de toekomst bvb de kleur door de gebruiker live in te laten stellen...

Ook dit soort 'spaceless'  code is onleesbaar:

            color: " . ($i > 12 ? "'".$kleur1."'": "'".$kleurg."'") . ",

Een paar extra spaties maakt het veel mooier toch?:

           color: " . ($i > 12 ? "'" . $kleur1 . "'" :  "'" . $kleurg . "'") . ",

**Comment by jvanderzande** [comment]
> Jos,
> 
> Ik vind de kleuren voor de p1 grafieken niet zo geslaagd.
> Ik heb bij mij nu een variant draaien waarbij de rgba kleuren in de config.php zijn opgenomen.
> Zal ik deze naar development uploaden?

Is prima Andre, dn kijk ik wat je ervan gemaakt hebt. De reden voor de verandering is om de kleuren meer te laten matchen.

**Comment by jvanderzande** [comment]
> Ook dit soort 'spaceless' code is onleesbaar:

Mee eens dat het anders kan, maar de huidige editor's hebben syntax coloring, dus ik heb weinig problemen de code te lezen.  
Een idee zo kunnen zijn dat we een standaard adopteren die door een van de bekende beautify programma gebruikt wordt, zodat er geen discussie is betreft "if's" op 1 lijn of niet; wel of niet spaties tussen operators .... en in ieder geval de leading and trailing spaces consequent krijgen en houden. 
Verder ben ik maar een coding amateur dus hoor graag hoe het beter kan.  ;-)

**Comment by mirakels** [comment]
ja ik gebruik syntax coloring, maar ondanks dat vindt ik het prettig lezen met de spaties.. 
en een beautifier erdoorheen is ook wel handig. Als we ons er dan allemaal aan proberen te houden wordt het nog professioneel ook ;)

**Comment by mirakels** [comment]
en ik ben ook geen professioneel developper hoor. HEt is voor het eerst dat ik echt met javascript speel.

**Comment by jvanderzande** [comment]
> > Jos,
> > Ik vind de kleuren voor de p1 grafieken niet zo geslaagd.
> > Ik heb bij mij nu een variant draaien waarbij de rgba kleuren in de config.php zijn opgenomen.
> > Zal ik deze naar development uploaden?
> 
> Is prima Andre, dn kijk ik wat je ervan gemaakt hebt. De reden voor de verandering is om de kleuren meer te laten matchen.

Even gekeken en het resultaat is prima zo en geeft de vrijheid de kleuren toe te kennen die men wil. Het enige lastige kan zijn dat men de kleuren zelf nu moet omzetten van 1 HEX RGB waarde naar de 3 DEC waarden en ze niet meer  hetzelfde zijn als de kleuren voor de Inverter. 
... maar voor mij is het prima, want ik weet hoe het is opgezet. ;-)

Het eindresultaat is nu wel mooi "strak"!

**Comment by mirakels** [comment]
Werkt bij jullie de daygraph en monthgraph goed? De Solar Retour en Solar Verbruik  zijn bij mij zwart. Als ik de fillOpacity uitcomment komen de kleuren wel weer terug...
Ik dacht dat het aan de oude highcharts lag, maar na legen cache en site data blijft het zwart...

**Comment by jvanderzande** [comment]
Bij mij werkt die goed met deze settings:
```
$kleurSR = 'rgba(0,153,0,0.7)';     // kleur Solar Retoer
$fillOpacitySR = 0.4;
$kleurSV = 'rgba(0,153,0,0.4)';     // kleur Solar Verbruik
$fillOpacitySV = 0.2;
$kleurVL = 'rgba(65,105,225,0.8)';  // kleur Verbruik Levering
$kleurVS = 'rgba(65,105,225,0.6)';  // kleur Verbruik Solar
$kleurS =  'rgba(255,0,0,0.9)';     // kleur schatting opbrengst solar
```
Kan je even aangeven wat jij hebt om hem fout te krijgen?

**Comment by mirakels** [comment]
Ik heb exact dezelfde kleuren, maar heb alleen $kleurSV = 'rgba(0,153,0,0.4)'; om het solar verbruik mooier te laten zien.
Maar zodra ik fillOpacity aanzet worden de areas zwart.

**Comment by jvanderzande** [comment]
> maar heb alleen $kleurSV = 'rgba(0,153,0,0.4)'; 

Jouw regel is toch precies hetzelfde als ik heb?

> Maar zodra ik fillOpacity aanzet worden de areas zwart.

Aanzetten betekent dat je // voor $fillOpacitySV = 0.2; weghaald?

**Comment by mirakels** [comment]
oops, $kleurSV = 'rgba(153,0,0,0.4)';

Nee ik zet in de zonnepanele.php een // voor de fillOpacity:

**Comment by jvanderzande** [comment]
met die aanpassingen krijg ik:
![image](https://user-images.githubusercontent.com/13818504/57725118-a9eea880-768c-11e9-9016-798c21f23138.png)
Email mij even jouw versie van config.php en zonnepanelen.php zodat ik ze even kan vergelijken met Winmerge om te zien waarom jij een andere uitkomst krijgt.

**Comment by jvanderzande** [comment]
Ik krijg dit met // voor fillOpacity:
![image](https://user-images.githubusercontent.com/13818504/57725260-0225aa80-768d-11e9-888b-dd00f918ee4a.png)
en dit zonder:
![image](https://user-images.githubusercontent.com/13818504/57725298-15d11100-768d-11e9-9f85-0b325c50ed6e.png)
Email me even jouw versie van zonnepanelen.php en config regels voor de kleuren, dan kijk ik even naar verschillen met mijn versie.

**Comment by mirakels** [comment]
ik heb nu de exacte zonnepanelen.ph en config.ph uit git overgenomen maar blijft zwart:

![image](https://user-images.githubusercontent.com/1038737/57727164-0fdd2f00-7691-11e9-845b-e0da88ef19ea.png)

**Comment by mirakels** [comment]
zoui toch mijn highcharts versie niet goed zijn.
Hoe kan ik zien welke versie door de browser gerbuikt wordt (firefox)?

**Comment by jvanderzande** [comment]
dat is de SR kleur... ...  Ik kan het niet repliceren dus heb echt even jouw bestanden config.php en zonnepanelen.php nodig om te kunnen testen.

**Comment by amrij** [comment]
Als ik $kleurSR = 'rgba(0,153,0,0.7)' vervang door $kleurSR = 'rgba(0,153,0,0,7)' dan krijg ik  hetzelfde als jij krijgt.

**Comment by jvanderzande** [comment]
Chrome developer mode/F12 : 
![image](https://user-images.githubusercontent.com/13818504/57727638-4cf5f100-7692-11e9-9129-c6162583447b.png)

**Comment by jvanderzande** [comment]
> Als ik $kleurSR = 'rgba(0,153,0,0.7)' vervang door $kleurSR = 'rgba(0,153,0,0,7)' dan krijg ik hetzelfde als jij krijgt.

Je bedoeld als er een komma "," wordt gebruikt ipv een decimal point "."?

**Comment by amrij** [comment]
Ja, dan wordt het helemaal zwart. Alleen bij mij is in het renvooi van de serie dan ook zwart.

**Comment by jvanderzande** [comment]
...  shit in is .....  ;-)
maw: het moet wel goed gedefinieerd worden anders werkt het niet goed.

**Comment by mirakels** [comment]
maar ik heb daar geen komma... 
Ik heb je de files gemaild jos.

**Comment by mirakels** [comment]
Oh, en ik heb ook met chrome getest, en daar zie ik dat ik inderdaad highcharts 7.1.1 gebruik, 
maar het geeft exact hetzelfde probleem als op firefox...
En als ik fillOpacity weer uitcomment in zonnepanelen.php krijg ik weer goed beeld...

**Comment by mirakels** [comment]
ik denk dat ik een antwoord heb. Als je naast color ook fillColor definieerd werkt het wel goed.
Ik maak wel even een patch die fillColor gelijk maakt aan color, en ze hem in het pull request.
Gek dat het bij andere graphs geen probleem is trouwens...

**Comment by jvanderzande** [comment]
Probeer eens om de waarde tussen quote te zetten:
`$fillOpacitySV = '0.2';`

Volgens mij wordt er door de server een conversie gedaan naar 0,2 toen ik het met mijn laptop lokaal testen.

**Comment by mirakels** [comment]
je bent een held Jos! die quotes did the trick.
Subtiel zeg

**Comment by mirakels** [comment]
Als het goed is kan je van een pull request een commit rejecten. Dus dan zou die fillColor coomit (en de 'merge' commit kunnen skippen.

**Comment by jvanderzande** [comment]
Ik zou niet weten hoe ik 1 commit van de hele PR kan rejecten. Ik weet wel hoe achteraf een revert te doen van een commit.  Jij bent de enige die dit kan aanpassen volgens mij.
Open voor suggesties. :-)

**Comment by mirakels** [comment]
hm, weer wat geleerd. pull request aangepast!

**Comment by spiralshapeturtle** [comment]
Waarom is de kleur codering van userfriendly naar itguru getransformeerd🤣?

In de config.php staan de beide kleur stellingen nog. Zijn ze beide nodig voor een correcte werking?

**Comment by jvanderzande** [comment]
> Waarom is de kleur codering van userfriendly naar itguru getransformeerd🤣?

Ik heb mijn mening daar al eerder over gegeven. 

> In de config.php staan de beide kleur stellingen nog. Zijn ze beide nodig voor een correcte werking?

Welke beide instellingen?  Alles staat en maar 1 keer in en is allemaal nodig.
Deze regels zijn voor de lijn van iedere serie en bevat de 3 kleuren en Opacity (transparantie)  voor de lijn zelf: 
`$kleurSR = 'rgba(0,153,0,0.7)';     // kleur Solar Retoer`

Deze regels zijn extra voor de Area series en geven de Opacity (transparantie) voor de het hele vlak:
`$fillOpacitySR = 0.4;`

All clear?

**Comment by spiralshapeturtle** [comment]
Ik heb geüpgraded en het blijft werken, ik zag dat deze versie nu de master is geworden. 👍

**Comment by jvanderzande** [comment]
Ik heb een aanpassing getest die het mogelijk maakt om de kleuren voor de grafieken allemaal in RGB hex te doen, maar kan ook in het oude formaat. Het mag dan dus dit huidige formaat zijn:
```
// inverter en panelen grafiek kleur actuele dag
// Hex Code #RRGGBB: '#4169E1', '#0000FF' .... zie https://www.rapidtables.com/web/color/
// Decimal Code(R,G,B): 'rgb(65,105,225)', 'rgb(0,0,255)' .... zie https://www.rapidtables.com/web/color/
$kleur = '#4169E1';  // kleur royalbleu voor actuele dag
$kleur1 = '#009900'; // kleur groen voor lijn voorafgaande dag inverter grafiek (grijs = '#d4d0d0')
$kleur2 = '#009900'; // kleur groen voor lijn actueel paneel
$kleurg = '#d4d0d0'; // kleur grijs voor lijn overige dagen / panelen
$Gem_Verm = '3' ;      // bereken het gemiddelde van x metingen om de grafiek wat minder te laten fluctueren
$kleurSR = 'rgba(0,153,0,0.7)';     // kleur Solar Retour
$fillOpacitySR = '0.4';               // opvul ondoorzichtigheid 0 = geheel doorzichtig, 0.5 is half doorzichtig 1 = ondoorzichtig
$kleurSV = 'rgba(0,153,0,0.4)';     // kleur Solar Verbruik
$fillOpacitySV = '0.2';
$kleurVL = 'rgba(65,105,225,0.8)';  // kleur Verbruik Levering
$kleurVS = 'rgba(65,105,225,0.6)';  // kleur Verbruik Solar
$kleurS =  'rgba(255,0,0,0.9)';     // kleur schatting opbrengst solar
```
Maar nu ook dit formaat om de setting eenduidiger te maken:
```
// inverter en panelen grafiek kleur actuele dag
// Hex Code #RRGGBB: '#4169E1', '#0000FF' .... zie https://www.rapidtables.com/web/color/
$kleur = '#4169E1';    // kleur royalbleu voor actuele dag
$kleur1 = '#009900';   // kleur groen voor lijn voorafgaande dag inverter grafiek (grijs = '#d4d0d0')
$kleur2 = '#009900';   // kleur groen voor lijn actueel paneel
$kleurg = '#d4d0d0';   // kleur grijs voor lijn overige dagen / panelen
$Gem_Verm = '3' ;      // bereken het gemiddelde van x metingen om de grafiek wat minder te laten fluctueren
$kleurSR = '#009900';  // kleur Solar Retour
$OpacitySR = '0.7';      // Lijn transparantie
$fillOpacitySR = '0.4';  // opvul transparantie
$kleurSV = '#009900';  // kleur Solar Verbruik
$OpacitySV = '0.4';      // Lijn transparantie
$fillOpacitySV = '0.2';  // opvul transparantie
$kleurVL = '#4169E1';  // kleur Verbruik Levering
$OpacityVL = '0.8';      // Lijn transparantie:
$kleurVS = '#4169E1';  // kleur Verbruik Solar
$OpacityVS = '0.6';      // Lijn transparantie
$kleurS =  '#FF0000';  // kleur schatting opbrengst solar
$OpacityS = '0.9';       // Lijn transparantie
```

Goed idee?
Jos

**Comment by amrij** [comment]
Voor de eenduidigheid is dit prima.

André

**Comment by jvanderzande** [comment]
Committed.
