### ISSUE TITLE
5min gemiddelde grafiek

### ISSUE THREAD

**Issue by spiralshapeturtle** [amrij/zonnepanelen#45]
Hallo

op dit moment plot de website de opbrengst realtime op basis van de SE 5min updates. Waardoor je alle pieken & dalen 1:1 plot. 

De histrische lijnen van de afgelopen 14 dagen zijn doordat er geen afronding is, behoorlijk in hoeveelheid aanwezig (denk aan; ||||||).  Daar kunnen we wat aan doen als we de grafiek ombouwen naar een grafiek met wat afronding, dan heb je niet zoveel last van die pieken en dalen lijnen op bewolkte dagen. Hierdoor blijft de grafiek ronder en verminder je het aantal verticale plots.

Een voorbeeld, en neem dan in gedachten dat wij in grijs nog 14 dagen plotten zonder afronding ;-)

Dit beeld is een stuk rustiger, zeker als je 14 dagen over elkaar plot.
<img width="814" alt="5min" src="https://user-images.githubusercontent.com/16855935/57573746-02276f80-742d-11e9-8f0e-e59be44ab82e.png">

Dit is realtime
<img width="823" alt="realtime" src="https://user-images.githubusercontent.com/16855935/57573743-f9369e00-742c-11e9-88b6-12c6831ef98d.png">

**Comment by jvanderzande** [comment]
Ik begrijp niet goed wat 5min gemiddeld is als je maar eens in de 5 minuten een update krijg. Bedoeld je een voortschrijdend gemiddelde  (moving Average) van de laatste x punten (of zoiets) ?

**Comment by jvanderzande** [comment]
Zit in laatste development versie.
