### ISSUE TITLE
PVGis contract period calculation bug

### ISSUE THREAD

**Issue by jvanderzande** [amrij/zonnepanelen#55]
There is an bug in the PVGis contract period calculation for me and showing a much to high value.
I have an fix running in test and will commit & push when tested properly.

Jos

**Comment by amrij** [comment]
The calculation is not correct.

**Comment by jvanderzande** [comment]
There was a mixup with var cdays beings used as the number of days in the current month and number of days in the contract start month. That is now changed in the last commit: https://github.com/amrij/zonnepanelen/commit/1e9222945bad328063354fad678930b1ac29f931 
It now has 2 variables: 
cdays -> number of days in current month 
con_days -> number of days in the contract start month 
Please double check if the right variable is now use it the formulas that are spread around.

**Comment by mirakels** [comment]
Yes this seems to fix it all together.

Although I have my droughts on the code in update_year(), especially around 'cdays'. Shouldn't that also be con_days?

(PS: before makeing furhter commits please check my pull request first...)

**Comment by jvanderzande** [comment]
> Although I have my droughts on the code in update_year(), especially around 'cdays'. Shouldn't that also be con_days?
> 

Which line specifically as in the PVGis contract period calculation is using both as it does require both?

> (PS: before makeing furhter commits please check my pull request first...)

I see you have my last commit in there as well. Aren't you creating a new branch for each change to avoid this?  I leave it to @amrij  to check and agree on renaming all date variables.

**Comment by mirakels** [comment]
After rechecking I think the calculation is ok. I was confused cdays was used there instead of con_cdays (line 975), but as the con_month an cm are the same it does not matter.
But it looks like the ajax call is made for every point in the con_month. Is that needed?

I sync my local branch with develop before adding my stuff. But here your commit is still separate from mine. so I don't understand...

**Comment by jvanderzande** [comment]
> But it looks like the ajax call is made for every point in the con_month. Is that needed?

You mean filling datam1?  There is an if there to only do that when the contract month is eq to the PVGis Month and easily checked by going in the Developer mode on your browser and looking at the network tab to see all API call made.

**Comment by mirakels** [comment]
Ah yes, the ychart only has datapoints per month.... 

I see why your commit is in the pull request. I accidentally did a pull request against master instead of development ;(
