### ISSUE TITLE
1.70 alle historie verdwenen

### ISSUE THREAD

**Issue by spiralshapeturtle** [amrij/zonnepanelen#61]
Andre

in de laatste versie is de historie van de vorige dagen verdwenen. Zoals de efficiëntie van gisteren en het gat tussen de opgebrachte energie en de nog benodigde energie. De mouseover van de inverter werkt ook niet.

@jvanderzande @amrij 

<img width="216" alt="image" src="https://user-images.githubusercontent.com/16855935/60753216-6569f400-9fcf-11e9-8324-f12c458d8000.png">

**Comment by amrij** [comment]
Heb je bij de update ook een update gedaan van de js files, de img/maan files en de css files?

**Comment by spiralshapeturtle** [comment]
Hey @amrij nope het is echt stuk, net even opnieuw opgebouwd maar nog steeds hetzelfde resultaat. 

Is het lastiger troubleshooten nu alles in 1 file staat? Misschien relatie met DSMR reader?

**Comment by amrij** [comment]
Indien je de oud DSMR file gebruikt gaat het dan wel goed?
Je kan in de config.php file de live-server-data-electra-dsmr.php nog gebruiken.

**Comment by spiralshapeturtle** [comment]
nee dat werkt ook nog niet, idee om deze change terug te draaien?

**Comment by amrij** [comment]
Indien dat niet werkt ligt het niet aan het samenvoegen van de live-server-data-electra files.
Bij de andere twee live-server-data-electra files werkt het wel. Aan zonnepanelen.php is niets veranderd.
In config.php is alleen de filenaam veranderd.
Werkt de versie in de Master wel bij jou.

**Comment by spiralshapeturtle** [comment]
nope master werkt ook niet, zo kwam ik erachter. De enige versie welke wel werkt is 1.69.2 meen ik uit mijn hoofd.

**Comment by jvanderzande** [comment]
Rob, zip de foute versie en email het even naar me, dan test ik hem voor je waar het fout gaat. ;-)

**Comment by amrij** [comment]
Op 24 mei is de DSMR file veranderd. Deze is op 30 mei in de master gezet. Dit was versie 1.69.0.
Wanneer heb je  de één na laatste keer de versie geüpload?

**Comment by jvanderzande** [comment]
Het lijkt op een cache issue, want soms doet hij het wel en soms niet, maar Ctrl+F5 laat de data van de SUM_BOX wel zien wanneer die leeg is. F12 laat ook zien dat hij totaal leeg is, en geeft geen errors. Ik  heb het niet mijn mijn locale kopie kunnen repliceren, dus geen idee door welke verandering dit is gebeurd. Deze setup is niet de allerlaatste versie, maar die geeft een andere Error bij mij. (zie #64 )

**Comment by jvanderzande** [comment]
@amrij, Wat denk jij? Ik neem aan dat door het samenvoegen van de scripts in een, en dus nu dezelfde URL wordt aangesproken, de browser regelmatig denkt dat hij de cached versie kan gebruiken. Ik zie in het zonnepanelen.php script meerdere ajax url calls waar de cache niet op false staat, dus misschien iets om mee testen?
Ik laat deze verder los qua testen/debuggen.

**Comment by spiralshapeturtle** [comment]
Het lijkt erop dat het wel eens deze oorzaak kan hebben Jos. Als jullie een
nieuwe versie hebben om te testen download ik hem even.

Rob


-- 
Groeten Rob.

**Comment by amrij** [comment]
Rob,

Je kunt de laatste versie downloaden.

André

**Comment by jvanderzande** [comment]
Laatste versie even getest en lijkt goed te werken. Hoop dat Rob's cache problem nu ook is opgelost.

**Comment by jvanderzande** [comment]
mmm, toch niet. Ik zie nu helemaal geen informatie in sum_text voor de vorige dagen. Werkt dat wel bij jou?

**Comment by jvanderzande** [comment]
In deze commit: https://github.com/amrij/zonnepanelen/commit/24ea18aa2cba4c4a895a9993c17d1adcf418dd81

is van huidige regel 2569  in zonnepanelen.php een comment van gemaakt en is zeer waarschijnlijk de reden dat het soms wel en soms niet werkte, en nu helemaal niet meer voor mij: 
`	 //				update_map_fields();`

Dit komt omdat in update_map_fields() gechecked wordt of de wchart en ychart objecten al gevuld zijn met data aangezien die worden gebruikt om de data te berekenen.  Vandaar dat die regel uitgevoerd moet worden.
Nadat ik het comment weer heb verwijderd werkt het weer voor mij

**Comment by amrij** [comment]
Bij mij werkt het in beide gevallen.
Ik zal de aangepaste versie uploaden.

**Comment by jvanderzande** [comment]
> Bij mij werkt het in beide gevallen.

Dat kan en heeft alles te maken met de snelheid waarop de P1 info in de wchart en ychart objecten wordt gezet. Het is een asynchrone race conditie, dus vandaar de extra call naar update_map_fields() en de test, maar ben er vrij zeker van dat dit het probleem van Rob zal oplossen. Waarom het nu bij mij ineens gebeurd weet ik niet, maar maakte de debuggen wel gemakkelijker.

**Comment by spiralshapeturtle** [comment]
Het ziet er goed uit! De development versie draait nu goed, misschien een idee om de caching weer in te schakelen, nu we weten dat het een code issue was? Zodat er efficiënter met resources en refreshes (snelheid?) wordt omgegaan?

**Comment by jvanderzande** [comment]
Mooi dat het weer werkt! 
Die caching opmerking moet je me even uitleggen. Caching heeft alleen zin als de gegevens statisch zijn en in dit geval willen we toch echt iedere keer de laatste informatie, dus caching van URL resultaten met actuele data moet juist voorkomen worden.  ;)

**Comment by spiralshapeturtle** [comment]
Ha Jos, nou het voelde wat trager vandaar dat ik daarover begon.
