### ISSUE TITLE
Error loading data and Days with 0 production missing

### ISSUE THREAD

**Issue by jvanderzande** [amrij/zonnepanelen#73]
Issue reported in the forum: https://gathering.tweakers.net/forum/list_message/66144702#66144702
stems from the fact that the the returned data for the series is negatieve hence invalid:
![SolarData_errorjpg](https://user-images.githubusercontent.com/13818504/108102512-eda7ea80-7088-11eb-8cb8-d8e3a2e68b3c.jpg)

I have a PR which fixes this issue and also will show the days that there was 0 production during the past snow covert days.

Jos

**Comment by jvanderzande** [comment]
André, In case we like to suppress the 0 entries in the early morning and evening, we could make this change to only show the 0 entries between 8:00-18:00:

```
	$de_day_total += $row["de_day"];
	$cHH = date("H", $row['timestamp']);
	if ($row["de_day"] > 0 || ($cHH > 8 && $cHH < 17) ) {
		$diff['serie']  = $dag[1];
		$diff['ts']    = intval($today + date("H", $row['timestamp']) * 3600 + round(0.2 * date("i", $row['timestamp'])) * 5 * 60) * 1000;
		$diff['vp'] = sprintf("%.3f", $de_day_total/1000);
		$diff['cp'] = $row['p_active'];
		# voeg het resultaat toe aan de total-array
		array_push($total, $diff);
	}
``` 
This will make the x-axis scale of the graph shorter and showing the graph a bit nicer.
Thoughts?

**Comment by amrij** [comment]
Yes, it's a bit nicer

**Comment by jvanderzande** [comment]
Agree..  do you want me to make a PR or will you make the change? (I have edited the code a little)
... and what about we also remove this line from genxAxis() to make the x-axis even "nicer"  by letting it start at the first value time?: 
`   startOnTick: true,`

Currently with this line:
![image](https://user-images.githubusercontent.com/13818504/108597413-34e3f300-7389-11eb-9507-d86eda7e038c.png)

Without this line:
![image](https://user-images.githubusercontent.com/13818504/108603384-e560ef80-73a7-11eb-852e-592038cbd36a.png)

**Comment by amrij** [comment]
You can make the changes.
