### ISSUE TITLE
geen grafiek sinds 1 aug.

### ISSUE THREAD

**Issue by slashw** [amrij/zonnepanelen#80]
op vrijdag 30jul is er 2x een stroomstoring geweest, op 28 en 29 juli is er maar een gedeelte in de grafiek te zien.
vanaf 1 augustus word de produktie wel geregistreerd maar is niet in de grafiek te zien.
Enig idee wat dat zou kunnen zijn?
![Schermafdruk van 2021-08-04 10-48-59](https://user-images.githubusercontent.com/65158830/128151732-7e39498c-879d-4297-ba36-eb9a201102bf.png)

**Comment by jvanderzande** [comment]
I had a similar issue a few weeks ago where it happens that the result contains 1 day more than the requested 14 days resulting it not showing today's data. The issue is related to the DST change. Try the attached version of live-server-data-60sec.php to see if that fixes your issue as well:
[live-server-data-60sec.zip](https://github.com/amrij/zonnepanelen/files/6932952/live-server-data-60sec.zip)
 Just rename your current version and unzip this version.
I will make a PR when it also fixes your issue.

**Comment by slashw** [comment]
I did what you suggested, still nothing, restarted the computer. Ill wait till tomorrow.
The log of apache is now after restart free of errors. Those where from 283 till 287 and 289 till 292, from live-server-data-60sec.
Watt i forgot to mention that when i stand on a panel, the information of that panel and the others are showing in the grafik.

**Comment by jvanderzande** [comment]
I would have to see the website to be able to determine what the issue is. 
Is there any chance of giving access for me remotely so I can have a look?
You can also EMail me on my GitHub email address when you like to take this "offline".

**Comment by slashw** [comment]
After the midnight restart there where more errors in the apache error log.
I am going to "reinstall" it with all the latest files and then see whats happening. (not shore is this can today)
If there still errors then (if you still want), you may take a look. And also go "offline"
Is yahoo your github e-mail address?

**Comment by slashw** [comment]
This is one error. 

![Schermafdruk van 2021-08-05 08-49-05](https://user-images.githubusercontent.com/65158830/128304883-2e438afa-aacd-4385-a38b-1134bcb256c6.png)

**Comment by jvanderzande** [comment]
> Is yahoo your github e-mail address?

Yes. 

I don't know those error messages, but doubt that is the reason for not showing any data for today.

**Comment by slashw** [comment]
Reinstall everything with the latest files, still the same only with more errors. Also with your file live-server-data-60sec.
It still stays the same.
I let it run for a while, see what specific errors are staying in the logger, and firefox. Also tried it with chrome, its the same. 
It looks like that only the graphics part is not working.

Thanks anyway.

**Comment by jvanderzande** [comment]
As I mentioned: I would have to have access to the website to debug what is happening in case you would like me to do that. :)

**Comment by slashw** [comment]
You got mail
